### ISSUE TITLE
2.3.1 release date?

### ISSUE THREAD

**Issue by bjornaadland** [noelex/GeographicLib.NET#31]
Hi, when do you plan on releasing 2.3.1?
The new features you added in 2.3.1-preview.1 works great (models from byte array),
but we cannot use it in production until it is part of a stable release.

Thanks!

**Comment by noelex** [comment]
[v2.3.1](https://www.nuget.org/packages/GeographicLib.NET/2.3.1) is now available on NuGet.

**Comment by bjornaadland** [comment]
Great, thanks alot.
