### ISSUE TITLE
Strong name validation fails when loading GeographicLib.dll from .NET Framework application

### ISSUE THREAD

**Issue by bjornaadland** [noelex/GeographicLib.NET#33]
GeographicLib.csproj supports strong name signing of assembly like this:

```
<SignAssembly>true</SignAssembly>
<AssemblyOriginatorKeyFile>SigningKey.snk</AssemblyOriginatorKeyFile>
<PublicSign>True</PublicSign>
```

We have experienced problems with assembly-loading of GeographicLib.dll on
some restricted machines because of this. This happens when trying to load
the assembly from a .NET Framework application. We get a FileLoadException that wraps a
SecurityException with HRESULT: 0x8013141A.

The problem seems to be the usage of `<PublicSign>true</PublicSign>`.
I don't know why `PublicSign` was added to the csproj file originally.

From Microsoft docs (https://github.com/dotnet/runtime/blob/main/docs/project/public-signing.md):
"Microsoft does not guarantee that you can successfully load public signed assemblies in all scenarios that are required for production use."

When verifying the signature in GeographicLib.dll, we get this:

```
C:\src\fn\GeographicLib.NET\GeographicLib\bin\Release\netstandard2.0>sn.exe -v GeographicLib.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.
```

I tested locally to remove the `<PublicSign>true</PublicSign>` from the csproj file, and the result is this:

```
C:\src\fn\GeographicLib.NET\GeographicLib\bin\Release\netstandard2.0>sn.exe -v GeographicLib.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'GeographicLib.dll' is valid
```

It would be greatly appreciated if you could remove the `<PublicSign>true</PublicSign>` from the csproj and produce an updated nuget package.

Thanks!
__

**Comment by noelex** [comment]
I chose to support Public Signing because this project was originally intended to target .NET Core and I wanted to avoid the drop-in replacement issue mentioned [here](https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md).

Since the signing key is checked in along with the sources code, so it might not be neccessary to support Public Signing anyway.

But I don't really want to publish a release just for this. So maybe I can turn it off in the next feature release. Does this work for you?

**Comment by bjornaadland** [comment]
Thanks for your quick reply.
We have a public release of our software in December, so it would be great to get this resolved as soon as possible.
Do you have a planned date for your next feature release?

**Comment by noelex** [comment]
I published a patch release with public signing turned off on netstandard2.0 and netstandard2.1. Please update and see if this fixes the issue.

**Comment by bjornaadland** [comment]
This fixes the issue. Thanks again, much appreciated.
